ArchaeoCod/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    #path('outline/', include('outline.urls')),
    path('outline/', include('outline.urls')),
    path('admin/', admin.site.urls),

]

outline/urls.py
from django.urls import path
from django.contrib import admin
from . import views

# TEMPLATE TAGGING
app_name = 'outline'

urlpatterns = [
    path('', views.index, name='index'),
    path('registration/', views.registration, name='registration'),
    path('tools/', views.import_tools, name='import_tools'),
    path('retouch/', views.retouch, name='retouch'),
    path('form_person/', views.form_person, name='form_person'),
    path('form_publication/', views.form_publication, name='form_publication'),
    path('logout/',views.user_logout,name='logout'),
    path('login/',views.user_login,name='login'),
    path('special/',views.special,name='special'),
]

outline/models.py
from django.db import models
from PIL import Image
from django.contrib.auth.models import User

# center of investigation, the physical artefact
class UserProfileInfo (models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    #additional attributes
    affiliation = models.CharField(max_length=200,blank=True)

    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username


class Artefact(models.Model):
    arte = models.CharField(max_length=200)
    arte_img = models.ImageField(upload_to=None, height_field=None, width_field=None, max_length=100,blank=True)
    rawmaterial = models.CharField(max_length=200,blank=True)
    type = models.CharField(max_length=200,blank=True)
    classification = models.CharField(max_length=200,blank=True)


# actor, publisher, drawer, multiple functions
class Person(models.Model):
    firstname = models.CharField(max_length=200,blank=True)
    surname = models.CharField(max_length=200,blank=True)
    title = models.CharField(max_length=200,blank=True)
    affiliation = models.CharField(max_length=200,blank=True)
    #email = models.EmailField(max_length=200,blank=True)

    def __str__(self):
        return self.firstname + ' ' + self.surname

#
class Publication(models.Model):
    people = models.ManyToManyField(Person)
    title = models.CharField(max_length=200,blank=True)
    subtitle = models.CharField(max_length=200,blank=True)
    publisher = models.CharField(max_length=200,blank=True)
    place = models.CharField(max_length=200,blank=True)
    doi = models.CharField(max_length=200,blank=True)
    journal = models.CharField(max_length=200,blank=True)
    issue = models.CharField(max_length=200,blank=True)
    ISBN = models.CharField(max_length=200,blank=True)

#
class Plate(models.Model):
    publications = models.ManyToManyField(Publication)
    person = models.ForeignKey(Person, on_delete=models.CASCADE,blank=True) # creator
    figurenumber = models.IntegerField(blank=True)
    page = models.IntegerField(blank=True)
    depictiontype = models.CharField(max_length=200,blank=True)
    plat_img = models.ImageField(upload_to=None, height_field=None, width_field=None, max_length=100,blank=True)


#
class Depiction(models.Model):
    plates = models.ManyToManyField(Plate)
    arte = models.ForeignKey(Artefact, on_delete=models.CASCADE,blank=True)#
    depiction_name = models.CharField(max_length=200,blank=True)
    pub_date = models.DateTimeField('date published',blank=True)
    outline = models.CharField(max_length=200,blank=True)
    depi_img = models.ImageField(upload_to=None, height_field=None, width_field=None, max_length=100,blank=True)


class Retouch_Depiction(models.Model):
    depi = models.ForeignKey(Depiction, on_delete=models.CASCADE)
    person = models.ForeignKey(Person, on_delete=models.CASCADE,blank=True)#) # Editor
    version = models.CharField(max_length=200,blank=True)
    rede_img = models.ImageField(upload_to=None, height_field=None, width_field=None, max_length=100,blank=True)

class Retouch (models.Model):
    rede = models.ForeignKey(Retouch_Depiction, on_delete=models.CASCADE)
    retouch_name = models.CharField(blank=True,max_length=200)
    length = models.FloatField(blank=True,max_length=200)
    location = models.CharField(blank=True,max_length=200)

#
class Metrics(models.Model):
    depi = models.ForeignKey(Depiction, on_delete=models.CASCADE)
    width = models.FloatField(blank=True)
    length = models.FloatField(blank=True)
    l_w_index = models.FloatField(blank=True)
    area = models.FloatField(blank=True)
    percent_area = models.FloatField(blank=True)
    contour_length = models.FloatField(blank=True)
    length_lower_part = models.FloatField(blank=True)
    length_upper_part = models.FloatField(blank=True)
    width_left_part = models.FloatField(blank=True)
    width_right_part = models.FloatField(blank=True)
    tip_angle = models.FloatField(blank=True)
    MP_CM_x_offset = models.FloatField(blank=True)
    MP_CM_y_offset = models.FloatField(blank=True)


#
class R_Import(models.Model):
    depi = models.ForeignKey(Depiction, on_delete=models.CASCADE)
    cluster = models.IntegerField(blank=True)

outline/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core import validators

from outline.models import Person,Publication,Plate,Depiction,Retouch_Depiction,Retouch,Metrics,R_Import,Artefact,UserProfileInfo


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields =('username','email','password')

class UserProfileInfoForm (forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('affiliation','profile_pic')


class FormName(forms.Form):
    firstname = forms.CharField(required = True)#, validators=[check_for_z])
    surname = forms.CharField(required = True)
    affiliation = forms.CharField(required = True)
    email = forms.EmailField()
    verify_email = forms.EmailField(label='Enter your email again:')

    def clean(self):
        all_clean_data = super().clean()

        email = all_clean_data['email']
        vmail = all_clean_data['verify_email']

        if email != vmail:
            raise forms.ValidationError('Make sure emails match!')

class Publication_Form (forms.ModelForm):

    # Form fields go here
    class Meta:
        model = Publication
        fields =  '__all__' #  '__all__'

# class NewUser_Form (forms.ModelForm):
#
#     # Form fields go here
#     class Meta:
#         model = Registration
#         fields =  '__all__' #  '__all__'



    # botcatcher = forms.CharField(required = False,
    #                 widget=forms.HiddenInput,
    #                 validators=[validators.MaxLengthValidator(0)])

    # def clean_botcatcher(self):
    #     botcatcher = self.cleaned_data['botcatcher']
    #
    #     if len (botcatcher)>0:
    #         raise forms.ValidationError('Gottcha Bot!')
    #
    #     return botcatcher

outline/views.py
from django.shortcuts import render
from django.http import HttpResponse

#
from outline import forms
from outline.models import Person,Publication,Plate,Depiction,Retouch_Depiction,Retouch,Metrics,R_Import,Artefact,UserProfileInfo

#
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Created views

def index (request):
    #ID = {'insert_ID':'!'}
    plate_list = Plate.objects.order_by('page')
    plate_dict = {'plate' : plate_list,'text':'hello world','number':10}

    return render(request,'outline/index.html',context = plate_dict)

@login_required
def special(request):
    return render (request,'outline/index.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('outline:index'))


# Add Author
def form_person(request):
    form = forms.FormName()

    if request.method == 'POST':
        form = forms.FormName(request.POST)

        if form.is_valid():
            #Do something code

            print ('validation success!')
            print (form.cleaned_data['firstname'])
            print (form.cleaned_data['surname'])
            print (form.cleaned_data['affiliation'])
            print (form.cleaned_data['email'])

    return render(request,'outline/form_person.html',{'form' :form})

# Add Publication
def form_publication (request):
    form = forms.Publication_Form()

    if request.method == 'POST':
        form = forms.Publication_Form(request.POST)

        if form.is_valid():
            #Do something code
            form.save()
            print ('validation success!')
            print (form.cleaned_data)

    return render(request,'outline/form_publication.html',{'form' :form})

def registration (request):
    registered = False

    if request.method == 'POST':

        user_form = forms.UserForm (data = request.POST)
        profile_form = forms.UserProfileInfoForm (data = request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            #Do something code
            user = user_form.save(commit=True)
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            register = True

            #return index(request)
        else:
            raise ValueError('Registration failed!')

    else:

        user_form = forms.UserForm ()
        profile_form = forms.UserProfileInfoForm ()

    return render(request,'outline/form_registration.html',
        {'user_form':user_form,
         'profile_form':profile_form,
         'registered':registered})

def user_login (request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('outline:index'))
            else:
                return HttpResponse('ACCOUNT NOT ACTIVE')
        else:
            print('Someone failed logging in')
            print('username:{} and password:{}'.format(username,password))
            return HttpResponse('invalid login details supplied!')
    else:
        return render(request,'outline/login.html',{})

def form_person(request):
    form = forms.FormName()

    if request.method == 'POST':
        form = forms.FormName(request.POST)

        if form.is_valid():
            #Do something code

            print ('validation success!')
            print (form.cleaned_data['firstname'])
            print (form.cleaned_data['surname'])
            print (form.cleaned_data['affiliation'])
            print (form.cleaned_data['email'])

    return render(request,'outline/form_person.html',{'form' :form})



def import_tools (request):
    ID = {'insert_ID':'tools!'}
    return render(request,'outline/retouch.html',context =ID)


def retouch (request):
    ID = {'insert_ID':'retouch!'}
    return render(request,'outline/retouch.html',context =ID)

templates/outline/base.html
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'outline:index' %}">Home</a></li>
          <li><a class="navbar-link" href="{% url 'outline:registration' %}">Register</a></li>

          {% if user.is_authenticated %}
            <li><a class="navbar-link" href="{% url 'outline:form_person' %}">Add Author</a></li>
            <li><a class="navbar-link" href="{% url 'outline:form_publication' %}">Add Publication</a></li>
            <li><a class="navbar-link" href= "#">Admin</a></li>
            <li><a class="navbar-link" href="#">Add Plate</a></li>
            <li><a class="navbar-link" href="#">Calculate Metrics</a></li>
            <li><a class="navbar-link" href="#">Calculate GMM</a></li>
            <li><a class="navbar-link" href="#">Create RDA</a></li>

            <li><a class="navbar-link" href="{% url 'outline:logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'outline:login' %}">Login</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
    <div class="">
      {% block body_block %}

      <!-- Anyting outside of this will be inherited if you extend! --!>

      {% endblock %}
    </div>


  </body>

</html>

templates/outline/form_person.html
<!DOCTYPE html>

{% extends "outline/base.html" %}
  {% block body_block %}
    <h1>Fill out the form:</h1>
    <div class='container'>
      <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-primary" value="Submit">
      </form>

    </div>
  {% endblock %}

templates/outline/form_publication.html
<!DOCTYPE html>

{% extends "outline/base.html" %}

  {% block body_block %}
    <h1>Fill out the form:</h1>
    <div class='container'>
      <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-primary" value="Submit">
      </form>

    </div>
  {% endblock %}

templates/outline/form_registration.html
<!DOCTYPE html>

{% extends "outline/base.html" %}
  {% load static %}
  {% block body_block %}
  <div class="jumbotron">
    {% if registered %}
      <h1>Thank you for your registration!</h1>
    {% else %}
    <h1>Registration</h1>
    <h2>Please register here and fill up the form:</h2>
    <form enctype="multipart/form-data" method="POST" >
      {% csrf_token %}
      {{ user_form.as_p }}
      {{ profile_form.as_p }}

      <input type="submit" class="btn btn-primary" value="Register">
      {% endif %}
    </form>
  </div>

  {% endblock %}

templates/outline/index.html
<!DOCTYPE html>

{% extends "outline/base.html" %}
  {% load static %}
  {% block body_block %}
      <div class="jumbotron">
        <h1>PyR - EnRA</h1>
      </div>

      <a href="{% url 'outline:form_person' %}">Bitte geben Sie hier einen neuen Autoren an</a>
      <a href="{% url 'outline:registration' %}">Registration</a>
      <br>

      <h2>{{ text|upper|cut:'W' }}</h2>
      <h2>{{ number|cut:'0' }}</h2>

      <h2> Here are your Publication data</h2>
      <div class="db_out_import">
        {% if plate %}

        <table >
          <thead>
            <th>page</th>
            <th>figure_number</th>
          </thead>
          {% for p in plate %}
          <tr>
            <td>{{ p.page }}</td>
            <td>{{ p.figure_number }}</td>

          </tr>
          {% endfor %}
        </table>
        {% else %}
          <p>NO plates found!</p>
        {% endif %}
      </div>

      <img src = "{% static "/images/pic.jpg " %}" alt = ''>
  {% endblock %}

templates/outline/login.html
<!DOCTYPE html>
{% extends 'outline/base.html' %}

  {% block body_block %}
    <div class="jumbotron">
      <h1>Please Login</h1>
      <form class="" action="{% url 'outline:login' %}" method="post">
        {% csrf_token %}
        <label for="username">Username:</label>
        <input type="text" name="username" placeholder="Enter Username">
        <label for="password">Password</label>
        <input type="text" name="password">
        <input type="submit" class="btn btn-primary" value="Login">
      </form>
    </div>
  {% endblock %}

templates/outline/retouch.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>PyR - EnRA : Retouch</title>
  </head>
  <body>
      <h1>PyR - EnRA : Retouch</h1>
      {{ insert_ID }}
  </body>
</html>